baseurl = "https://ellisonleao.github.io/"
languageCode = "pt-br"
theme = "hugo-vitae"
paginate = 5
defaultContentLanguage = "pt-br"
pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
title = "Ellison Leão"

[params]
    avatar = "/img/logo-site.png"
    contentTypeName = "posts"
    goatCounter = "ellisonleao"
    listAuthor = true
    subtitle = "Polyrhythm programming"
    arc = "8fssWjDK"
    customCSS = "overrides.css"

    [[params.social]]
        name = "Github"
        icon = "fab fa-github"
        url = "https://github.com/ellisonleao/"

    [[params.social]]
        name = "Twitch"
        icon = "fab fa-twitch"
        url = "https://twitch.tv/npxbr"

    [[params.social]]
        name = "Twitter"
        icon = "fab fa-twitter"
        url = "https://twitter.com/ellisonleao"

    [[params.social]]
        name = "Linkedin"
        icon = "fab fa-linkedin"
        url = "https://linkedin.com/in/ellisonleao"

    [[params.social]]
        name = "RSS"
        icon = "fas fa-rss"
        url = "/index.xml"

[languages]
    [languages.pt-br]
        [languages.pt-br.menu]
            [[languages.pt-br.menu.main]]
                identifier = "about"
                name = "Sobre mim"
                url = "/about"
                weight = 1
            [[languages.pt-br.menu.main]]
                identifier = "posts"
                name = "Blog"
                url = "/posts"
                weight = 2
         [[languages.pt-br.menu.main]]
                identifier = "tags"
                name = "Tags"
                url = "/tags"
