baseurl = "https://ellisonleao.github.io/"
languageCode = "pt-br"
theme = "terminal"
paginate = 5
defaultContentLanguage = "pt-br"

[params]
  contentTypeName = "posts"
  themeColor = "green"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false
  goatCounter = "ellisonleao"

[languages]
  [languages.pt-br]
    title = "Ellison Leão"
    subtitle = "Polyrhythm programming"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.pt-br.params.logo]
      logoText = "Polyrhythm programming"
      logoHomeLink = "/"

    [languages.pt-br.menu]
      [[languages.pt-br.menu.main]]
        identifier = "about"
        name = "Sobre mim"
        url = "/about"
